name: modeling_lanternfly_populations
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - ruff
  - pytest
  - pip:
    - python-dotenv
    - mkdocs
    - -e .