name: lanternfly_model
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - ruff
  - pytest
  - numpy
  - scipy
  - geopandas
  - shapely
  - pyarrow
  - scikit-learn
  - jupyter
  - pip:
    - daft-pgm
    - pgmpy
    - pyagrum
    - cloudpickle
    - pymc
    - arviz
    - uqpy
    - pyinaturalist
    - python-dotenv
    - mkdocs
    - pysal
    - -e .